// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0oEaLFHSmKDAFlzr4sbGLdvxUa7z2vPk',
    appId: '1:448352810413:android:63dcff52dc10b4eb251d24',
    messagingSenderId: '448352810413',
    projectId: 'jobhunt-97208',
    storageBucket: 'jobhunt-97208.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwUWJBiq49mCEwCYZOnhqmAuls7ombwOg',
    appId: '1:448352810413:ios:37ae6b460d77a45b251d24',
    messagingSenderId: '448352810413',
    projectId: 'jobhunt-97208',
    storageBucket: 'jobhunt-97208.appspot.com',
    androidClientId: '448352810413-1ai3dsb2ae0nj1ngk5iso1ogkthh05mb.apps.googleusercontent.com',
    iosClientId: '448352810413-0ea5s8l0tb760m9550bj8h6io2ulcg95.apps.googleusercontent.com',
    iosBundleId: 'com.united7.jobhuntFtl',
  );
}
