import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Hello': 'Hello',
          'App_Name': 'JobsHunt',
          'Email': 'Email',
          'Password': 'Password',
          'Login': 'Login',
          'Search': 'Search',
          'Recommend_Job': 'Recommend Job',
          'Best_Job': 'Best Job',
          'Verified_Companies': 'Verified Companies',
          'No_Data': 'No Data',
          'Your_Profile': 'Your Profile',
          'Your_Inbox': 'Your Inbox',
          'Your_Job_Status': 'Your Job Status',
          'Your_Job_Saved': 'Your Job Saved',
          'Your_Following_Company': 'Your Following Company',
          'Job_Recommend_Setting': 'Job Recommend Setting',
          'Notification': 'Notification',
          'Setting': 'Setting',
          'About': 'About',
          'Exit': 'Exit',
          'Fullname': 'Fullname',
          'Display_Name': 'Display Name',
          'Phone': 'Phone',
          'Address': 'Address',
          'Province': 'Province',
          'District': 'District',
          'Ward': 'Ward',
          'Road_Street': 'Road/Street',
          'Birthday': 'Date of Birth',
          'Education': 'Education',
          'Want_Job': 'Want To Find Job',
          'Account_Level': 'Your Account Level',
          'Role': 'Role',
          'Salary': 'Salary',
          'Min_Salary': 'Min Salary',
          'Max_Salary': 'Max Salary',
          'Currency': 'Currency',
          'Done': 'Done',
          'Update': 'Update',
          'Select': 'Select',
          'Guest': 'Guest',
          'Successful': 'Successful',
          'Unsuccessful': 'Unsuccessful',
          'Not_Full_Data': 'Please add full data',
          'Sign_In_With': 'Sign in with',
          'Dont_Have_Acc': 'Don\'t have an account?',
          'Sign_Up_Now': 'Sign Up Now',
          'Or': 'Or',
          'Using_App_Without': 'Using app without an account',
          'Register': 'Register',
          'Have_Acc': 'You have an account?',
          'Sign_In_Now': 'Sign In Now',
          'Password_Again': 'Password Again',
          'Read_Accepted': 'I have read and accepted to the',
          'Terms_Conditions': 'Terms and Conditions',
          'Candidate': 'Candidate',
          'Recruiter': 'Recruiter',
          'Remember': 'Remember',
          'Forget_Pass': 'Forget Password',
          'Need_Same_Pass': 'Two Passwords must be same',
          'Email_Validation': 'Please enter a valid email address.',
          'You_Are': 'You are',
          'Welcome_to': 'Welcome to',
          'Please_Set_Role': 'Please set your role to continue.',
          'Cancel': 'Cancel',
          'ThatsRight': 'That\'s right',
          'Website': 'Website',
          'Description': 'Description',
          'OK': 'OK',
          'CV_Today': 'Applied CV Today',
          'Posted_Jobs': 'Your Posted Jobs',
          'Company_Name': 'Name of Company',
          'Name_Job': 'Name of Job',
          'Year_Experience': 'Years of Experience',
          'Type_Job': 'Type of Job',
          'Number_Candidate': 'Number of Candidate',
          'Job_Detail': 'Job Detail',
          'Candidate_Requirement': 'Candidate Requirements',
          'Job_Benefit': 'Job Benefits',
          'Tag': 'Tag',
          'Deadline': 'Deadline',
          'Active': 'Active',
          'Argeement': 'Argeement',
          'Disagreement': 'Disagreement',
          'Intern': 'Intern',
          'Part_Time': 'Part-Time',
          'Full_Time': 'Full-Time',
          'Apply_Now': 'Apply Now',
          'Information': 'Information',
          'Person': 'Persons',
          'Check_CV': 'Check CVs',
          'Your_CV': 'Your CV',
          'Create_CV': 'Create CV',
          'Upload_CV': 'Upload CV',
          'Manager_CV': 'CV Manager',
          'Press_Choose': 'Press to choose your file',
          'Upload': 'Upload',
          'Supported_File': 'Supported File',
          'Maximium_Size': 'Maximium File Size',
          'Waiting': 'Waiting',
          'Having': 'You\'re still having file. Do you want to choose again?',
          'Created_CV': 'Created CV',
          'Uploaded_CV': 'Upload CV',
          'Create': 'Create',
          'Select_CV': 'Select Your CV',
          'View_CV': 'View CV',
          'View_Selected_CV': 'View Your Selected CV',
          'Confirm': 'Confirm',
          'Apporve': 'Apporve',
          'Reject': 'Reject',
          'Company': 'Company',
          'Sent_Time': 'Sent Time',
          'Status': 'Status',
          'View_Job': 'View Job',
          'View_All': 'View All',
          'Language': 'Language',
          'English': 'English',
          'Vietnamese': 'Vietnamese',
          'Theme': 'Theme',
          'Upgrade': 'Upgrade',
          'All_Appications': 'All Appications',
          'Dark': 'Dark',
          'Light': 'Light',
          'Detail': 'Detail',
          'Interview_Time': 'Interview Time',
          'See_more': 'See more',
          'Collapse': 'Collapse',
          'Gender': 'Gender',
          'Male': 'Male',
          'Female': 'Female',
          'Other': 'Other',
          'Place_Job': 'Place To Find Job',
          'Less_Than': 'Less than',
          'Year': 'Year',
          'Introduction': 'Introduction',
          'News_Recruitment': 'News recruitment',
          'Company_Follow': 'Follow the company',
          'Following': 'Following',
          'Content_Dialog_Unfollow':
              'When you unfollow, you will no longer receive recruitment information from this company. Do you want to continue?',
          'Unfollow': 'Unfollow',
          'Send_OTP': 'Send OTP',
          'Account_Authentication': 'Account Authentication',
          'Enter_the_verification_code_sent_to_your_email':
              'Enter the verification code sent to your email',
          'Get_OTP': 'Get OTP',
          'OTP_fail': 'OTP fail',
          'Something_Wrong': 'Something is wrong',
          'Resend_OTP': 'Resend OTP',
          'Email_is_not_exist': 'Email is not exist',
          'Change_Password': 'Change Password',
          'New_Password': 'New Password',
          'Confirm_Password': 'Confirm Password',
          'I_agree_to_change_my_password.': 'I agree to change my password.',
          'Password_changed_successfully!': 'Password changed successfully!',
          'Payment': 'Payment',
          'month': 'Month',
          'year': 'Year',
          'Only': 'Only',
          'Day': 'Day',
          'Update_account_line1': 'Update account to Premium',
          'Update_account_line2': 'Choose Your bundle',
          'Oder': 'Oder',
          'Payment_done': 'Payment done Successfully',
          'You_will':
              'You will be redirected to the home page shortly\nor click here to return to home page',
          'Continue': 'Continue',
          'Pls_Email_And_Check':
              'Please add your email and check the Terms and Conditions',
          'Email_Exist':
              'This email has exist in JobsHunt. Do you want to sign in?',
          'Sign_Up_Failed': 'Sign Up Failed',
          'Yes': 'Yes',
          'No': 'No',
          'Headquarter': 'Headquarter',
          'Check': 'Check',
          'Thousands': 'Thousands',
          'Millions': 'Millions',
          'Billions': 'Billions',
          'No_Experience_Required': 'No Experience Required',
          'Delete': 'Delete',
          'Pls_Enter_Password': 'Please enter the password',
          'Need_6p_Char': 'Need more than 6 characters',
          'No_Space': 'Doesn\'t use space',
          'And': 'and',
          'Phone_Less_11': 'Phone number can\'t have more than 11 numbers',
          'Phone_More_9': 'Phone number must have more than 9 numbers',
          'Chat': 'Chat',
          'Active_Job': 'Active Job',
          'Tax_Code': 'Tax Code',
          'Tax_Code_Must_10': 'Tax code must have 10 numbers',
          'Message':'Message'

        },
        'vi_VN': {
          'Hello': 'Xin Chào',
          'App_Name': 'JobsHunt',
          'Email': 'Email',
          'Password': 'Mật khẩu',
          'Login': 'Đăng nhập',
          'Search': 'Tìm Kiếm',
          'Recommend_Job': 'Công Việc Gợi Ý',
          'Best_Job': 'Công Việc Tốt Nhất',
          'Verified_Companies': 'Công Ty Được Xác Thực',
          'No_Data': 'Không Có Dữ Liệu',
          'Your_Profile': 'Hồ Sơ Của Bạn',
          'Your_Inbox': 'Hòm Thư Của Bạn',
          'Your_Job_Status': 'Tình Trạng Công Việc',
          'Your_Job_Saved': 'Công Việc Đã Lưu',
          'Your_Following_Company': 'Công Ty Đang Theo Dõi',
          'Job_Recommend_Setting': 'Cài Đặt Công Việc Gợi Ý',
          'Notification': 'Thông Báo',
          'Setting': 'Cài Đặt',
          'About': 'Giới Thiệu',
          'Exit': 'Thoát',
        },
      };
}
