import 'package:get/get.dart';
import 'package:jobhunt_ftl/blocs/app_riverpod_object.dart';

class LocaleString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Hello': 'Hello',
          'App_Name': 'FPLWork',
          'Email': 'Email',
          'Password': 'Password',
          'Login': 'Login',
          'Search': 'Search',
          'Recommend_Job': 'Recommend Job',
          'Best_Job': 'Best Job',
          'Premium_Companies': 'Premium Companies',
          'No_Data': 'No Data',
          'Your_Profile': 'Your Profile',
          'Your_Inbox': 'Your Inbox',
          'Your_Job_Status': 'Your Job Status',
          'Your_Job_Saved': 'Your Job Saved',
          'Your_Following_Company': 'Your Following Company',
          'Job_Recommend_Setting': 'Job Recommend Setting',
          'Notification': 'Notification',
          'Setting': 'Setting',
          'About': 'About',
          'Exit': 'Exit',
          'Fullname': 'Fullname',
          'Display_Name': 'Display Name',
          'Phone': 'Phone',
          'Address': 'Address',
          'Province': 'Province',
          'District': 'District',
          'Ward': 'Ward',
          'Road_Street': 'Road/Street',
          'Birthday': 'Date of Birth',
          'Education': 'Education',
          'Want_Job': 'Want To Find Job',
          'Account_Level': 'Your Account Level',
          'Role': 'Role',
          'Salary': 'Salary',
          'Min_Salary': 'Min Salary',
          'Max_Salary': 'Max Salary',
          'Currency': 'Currency',
          'Done': 'Done',
          'Update': 'Update',
          'Select': 'Select',
          'Guest': 'Guest',
          'Successful': 'Successful',
          'Unsuccessful': 'Unsuccessful',
          'Not_Full_Data': 'Please add full data',
          'Sign_In_With': 'Sign in with',
          'Dont_Have_Acc': 'Don\'t have an account?',
          'Sign_Up_Now': 'Sign Up Now',
          'Or': 'Or',
          'Using_App_Without': 'Using app without an account',
          'Register': 'Register',
          'Have_Acc': 'You have an account?',
          'Sign_In_Now': 'Sign In Now',
          'Password_Again': 'Password Again',
          'Read_Accepted': 'I have read and accepted to the',
          'Terms_Conditions': 'Terms and Conditions',
          'Candidate': 'Candidate',
          'Recruiter': 'Recruiter',
          'Remember': 'Remember',
          'Forget_Pass': 'Forget Password',
          'Need_Same_Pass': 'Two Passwords must be same',
          'Email_Validation': 'Please enter a valid email address.',
          'You_Are': 'You are',
          'Welcome_to': 'Welcome to',
          'Please_Set_Role': 'Please set your role to continue.',
          'Cancel': 'Cancel',
          'ThatsRight': 'That\'s right',
          'Website': 'Website',
          'Description': 'Description',
          'OK': 'OK',
          'CV_Month': 'CVs of this month',
          'Posted_Jobs': 'Your Posted Jobs',
          'Company_Name': 'Name of Company',
          'Name_Job': 'Name of Job',
          'Year_Experience': 'Years of Experience',
          'Type_Job': 'Type of Job',
          'Number_Candidate': 'Number of Candidate',
          'Job_Detail': 'Job Detail',
          'Candidate_Requirement': 'Candidate Requirements',
          'Job_Benefit': 'Job Benefits',
          'Tag': 'Tag',
          'Deadline': 'Deadline',
          'Active': 'Active',
          'Argeement': 'Argeement',
          'Disagreement': 'Disagreement',
          'Intern': 'Intern',
          'Part_Time': 'Part-Time',
          'Full_Time': 'Full-Time',
          'Apply_Now': 'Apply Now',
          'Information': 'Information',
          'Person': 'Persons',
          'Check_CV': 'Check CVs',
          'Your_CV': 'Your CV',
          'Create_CV': 'Create CV',
          'Upload_CV': 'Upload CV',
          'Manager_CV': 'CV Manager',
          'Press_Choose': 'Press to choose your file',
          'Upload': 'Upload',
          'Supported_File': 'Supported File',
          'Maximium_Size': 'Maximium File Size',
          'Waiting': 'Waiting',
          'Having': 'You\'re still having file. Do you want to choose again?',
          'Created_CV': 'Created CV',
          'Uploaded_CV': 'Upload CV',
          'Create': 'Create',
          'Select_CV': 'Select Your CV',
          'View_CV': 'View CV',
          'View_Selected_CV': 'View Your Selected CV',
          'Confirm': 'Confirm',
          'Approve': 'Approve',
          'Reject': 'Reject',
          'Company': 'Company',
          'Sent_Time': 'Sent Time',
          'Status': 'Status',
          'View_Job': 'View Job',
          'View_All': 'View All',
          'Language': 'Language',
          'English': 'English',
          'Vietnamese': 'Vietnamese',
          'Theme': 'Theme',
          'Upgrade': 'Upgrade',
          'All_Applications': 'All Applications',
          'Dark': 'Dark',
          'Light': 'Light',
          'Detail': 'Detail',
          'Interview_Time': 'Interview Time',
          'See_more': 'See more',
          'Collapse': 'Collapse',
          'Gender': 'Gender',
          'Male': 'Male',
          'Female': 'Female',
          'Other': 'Other',
          'Place_Job': 'Place To Find Job',
          'Less_Than': 'Less than',
          'Year': 'Year',
          'Introduction': 'Introduction',
          'News_Recruitment': 'News recruitment',
          'Company_Follow': 'Follow the company',
          'Following': 'Following',
          'Content_Dialog_Unfollow':
              'When you unfollow, you will no longer receive recruitment information from this company. Do you want to continue?',
          'Unfollow': 'Unfollow',
          'Send_OTP': 'Send OTP',
          'Account_Authentication': 'Account Authentication',
          'Enter_the_verification_code_sent_to_your_email':
              'Enter the verification code sent to your email',
          'Get_OTP': 'Get OTP',
          'OTP_fail': 'OTP fail',
          'Something_Wrong': 'Something is wrong',
          'Resend_OTP': 'Resend OTP',
          'Email_is_not_exist': 'Email is not exist',
          'Change_Password': 'Change Password',
          'New_Password': 'New Password',
          'Confirm_Password': 'Confirm Password',
          'I_agree_to_change_my_password.': 'I agree to change my password.',
          'Password_changed_successfully!': 'Password changed successfully!',
          'Payment': 'Payment',
          'month': 'Month',
          'year': 'Year',
          'Only': 'Only',
          'Day': 'Day',
          'Update_account_line1': 'Update account to Premium',
          'Update_account_line2': 'Choose Your bundle',
          'Oder': 'Oder',
          'Payment_done': 'Payment done Successfully',
          'You_will':
              'You will be redirected to the home page shortly\nor click here to return to home page',
          'Continue': 'Continue',
          'Pls_Email_And_Check':
              'Please add your email and check the Terms and Conditions',
          'Email_Exist':
              'This email has exist in JobsHunt. Do you want to sign in?',
          'Sign_Up_Failed': 'Sign Up Failed',
          'Yes': 'Yes',
          'No': 'No',
          'Headquarter': 'Headquarter',
          'Check': 'Check',
          'Thousands': 'Thousands',
          'Millions': 'Millions',
          'Billions': 'Billions',
          'No_Experience_Required': 'No Experience Required',
          'Delete': 'Delete',
          'Pls_Enter_Password': 'Please enter the password',
          'Need_6p_Char': 'Need more than 6 characters',
          'No_Space': 'Doesn\'t use space',
          'And': 'and',
          'Phone_Less_11': 'Phone number can\'t have more than 11 numbers',
          'Phone_More_9': 'Phone number must have more than 9 numbers',
          'Chat': 'Chat',
          'Available_Job': 'Available Job',
          'Tax_Code': 'Tax Code',
          'Tax_Code_Must_10': 'Tax code must have 10 numbers',
          'Message': 'Message',
          'Edit': 'Edit',
          'Set_Time': 'Set Time',
          'Set_Date': 'Set Date',
          'Premium': 'Premium',
          'Basic': 'Basic',
          'Number_Available_Jobs': 'Number of Available Jobs',
          'Reset': 'Reset',
          'All_Companies': 'All Companies',
          'Premium_Expiry_Date': 'Expiry Date of Premium',
          'Payment_History': 'Payment history',
          'Type_bank': 'Type - bank',
          'Price': 'Price',
          'Date_Created': 'Date created',
          'STT': '#',
          'Term':
              '\t\t\tBy accessing or using the FPL Work software, services, or any applications provided by FPL Work (jobshunt.info), collectively referred to as "Services," regardless of the means of access, you agree to be bound by these Terms of Use ("Terms"). The Services are owned or controlled by FPL Work, and these Terms affect your legal rights and obligations. If you do not agree to be bound by all of these Terms, do not access or use the Services. If you have any questions regarding these Terms, please contact us.\n\t\t\tWe may update these Terms of Use over time for legal reasons or to allow for the proper functioning of the FPL Work software. Any changes will be notified to you through an appropriate notice on our website. These changes will apply to the use of the FPL Work website. After we have notified you, if you do not wish to accept the updated Terms of Use, you should not continue to use the FPL Work software. If you continue to use the FPL Work software after the Terms of Use are updated, you must accept FPL Work\'s Terms of Use by choosing to agree through the notice displayed on our website when the changes are applied.',
          'Reporting_Reason': 'Reason',
          'Other_Reasons': 'Other reasons',
          'One_Reason': 'This post has signs of fraud',
          'Two_Reason': 'The informations are incorrect',
          'Three_Reason': 'Fill in your reason',
          'Report': 'Report',
          'Report_Company_Reminder':
              'Learn carefully about the recruiting company and the position you want to apply for. Be cautious about issues such as requiring fees or unclear, ambiguous contracts. If you have any problem in the company\'s job posting, please report them to us.',
          'Want_Exit': 'Do you want to exit?',
          'View_Profile': 'View Profile',
          'Has': 'Has',
          'Warning':
              'You have reached the limit of this function. Please update PREMIUM if you want to continue.',
          'CV_Full':
              'You have reached the limit of CV Manager (Max 3 CVs/account). Please update PREMIUM if you want to save more.',
          'Report_User_Reminder':
              'Learn carefully about the candidate you want to accept. Be cautious about issues such as spam, abuse or harrassment action. If you have any problem of this candidate, please report them to us.',
          'Two_Reason_2': 'Abuse or harrassment action',
          'Splash_Title': 'Find a perfect job',
          'Splash_Tile':
              'Find your dream job is easier and faster with FPLWork',
          'Get_Started': 'Let\'s Get Started',
          'Hold_Delete': 'Hold a CV you want to delete',
          'No_Available': 'This job is no longer available.',
          'Require': 'Require',
          'THANK_YOU': 'Thank You',
          'This_Acc_Banned': 'This account has been banned by Admin.',
        },
        'vi_VN': {
          'Hello': 'Xin Chào',
          'App_Name': 'FPLWork',
          'Email': 'Email',
          'Password': 'Mật khẩu',
          'Login': 'Đăng nhập',
          'Search': 'Tìm Kiếm',
          'Recommend_Job': 'Công Việc Gợi Ý',
          'Best_Job': 'Công Việc Tốt Nhất',
          'Premium_Companies': 'Công Ty Cao Cấp',
          'No_Data': 'Không Có Dữ Liệu',
          'Your_Profile': 'Hồ Sơ Của Bạn',
          'Your_Inbox': 'Hòm Thư Của Bạn',
          'Your_Job_Status': 'Tình Trạng Công Việc',
          'Your_Job_Saved': 'Công Việc Đã Lưu',
          'Your_Following_Company': 'Công Ty Đang Theo Dõi',
          'Job_Recommend_Setting': 'Cài Đặt Công Việc Gợi Ý',
          'Notification': 'Thông Báo',
          'Setting': 'Cài Đặt',
          'About': 'Giới Thiệu',
          'Exit': 'Thoát',
          'Fullname': 'Họ tên',
          'Display_Name': 'Tên hiển thị',
          'Phone': 'SĐT',
          'Address': 'Địa chỉ',
          'Province': 'Tỉnh/Thành phố',
          'District': 'Quận/Huyện',
          'Ward': 'Xã/Phường',
          'Road_Street': 'Đường/Phố',
          'Birthday': 'Ngày sinh',
          'Education': 'Giáo dục',
          'Want_Job': 'Muốn tìm công việc',
          'Account_Level': 'Tình trạng tài khoản',
          'Role': 'Vai trò',
          'Salary': 'Mức lương',
          'Min_Salary': 'Mức lương thấp nhất',
          'Max_Salary': 'Mức lương cao nhất',
          'Currency': 'Loại tiền tệ',
          'Done': 'Hoàn tất',
          'Update': 'Cập nhật',
          'Select': 'Chọn',
          'Guest': 'Khách',
          'Successful': 'Thành công',
          'Unsuccessful': 'Không thành công',
          'Not_Full_Data': 'Vui lòng điền đủ thông tin',
          'Sign_In_With': 'Đăng nhập bằng',
          'Dont_Have_Acc': 'Không có tài khoản?',
          'Sign_Up_Now': 'Đăng ký ngay',
          'Or': 'Hoặc',
          'Using_App_Without': 'Sử dụng mà không cần tài khoản',
          'Register': 'Đăng ký',
          'Have_Acc': 'Đã có tài khoản?',
          'Sign_In_Now': 'Đăng nhập ngay',
          'Password_Again': 'Nhập lại mật khẩu',
          'Read_Accepted': 'Tôi đã đọc và chấp thuận',
          'Terms_Conditions': 'Các điều khoản dịch vụ',
          'Candidate': 'Ứng viên',
          'Recruiter': 'Nhà tuyển dụng',
          'Remember': 'Ghi nhớ',
          'Forget_Pass': 'Quên mật khẩu',
          'Need_Same_Pass': '2 mật khẩu phải trùng nhau',
          'Email_Validation': 'Vui lòng điền Email',
          'You_Are': 'Bạn là',
          'Welcome_to': 'Chào mừng',
          'Please_Set_Role': 'Vui lòng chọn vai trò để tiếp tục.',
          'Cancel': 'Hủy bỏ',
          'ThatsRight': 'Đúng vậy',
          'Website': 'Website',
          'Description': 'Mô tả',
          'OK': 'OK',
          'CV_Month': 'CV trong tháng này',
          'Posted_Jobs': 'Những công việc đã đăng',
          'Company_Name': 'Tên công ty',
          'Name_Job': 'Tên công việc',
          'Year_Experience': 'Năm kinh nghiệm',
          'Type_Job': 'Loại công việc',
          'Number_Candidate': 'Số ứng viên',
          'Job_Detail': 'Chi tiết',
          'Candidate_Requirement': 'Yêu cầu ứng viên',
          'Job_Benefit': 'Quyền lợi',
          'Tag': 'Tag',
          'Deadline': 'Ngày hết hạn',
          'Active': 'Kích hoạt',
          'Argeement': 'Thỏa thuận',
          'Disagreement': 'Lương cứng',
          'Intern': 'Thực tập sinh',
          'Part_Time': 'Bán thời gian',
          'Full_Time': 'Toàn thời gian',
          'Apply_Now': 'Ứng tuyển',
          'Information': 'Thông tin',
          'Person': 'Người',
          'Check_CV': 'Kiểm tra CV',
          'Your_CV': 'CV của bạn',
          'Create_CV': 'Tạo CV',
          'Upload_CV': 'Tải CV lên',
          'Manager_CV': 'Quản lý CV',
          'Press_Choose': 'Nhấn để chọn file',
          'Upload': 'Tải lên',
          'Supported_File': 'File hỗ trợ',
          'Maximium_Size': 'Dung lượng tối đa file',
          'Waiting': 'Đợi',
          'Having': 'Bạn đang có file. Bạn có muốn chọn lại?',
          'Created_CV': 'CV đã tạo',
          'Uploaded_CV': 'CV đã tải lên',
          'Create': 'Tạo',
          'Select_CV': 'Chọn CV',
          'View_CV': 'Xem CV',
          'View_Selected_CV': 'Xem CV đã chọn',
          'Confirm': 'Chấp nhận',
          'Approve': 'Chấp thuận',
          'Reject': 'Từ chối',
          'Company': 'Công ty',
          'Sent_Time': 'Thời gian gửi',
          'Status': 'Trạng thái',
          'View_Job': 'Xem công việc',
          'View_All': 'Xem tất cả',
          'Language': 'Ngôn ngữ',
          'English': 'Tiếng Anh',
          'Vietnamese': 'Tiếng Việt',
          'Theme': 'Chủ đề',
          'Upgrade': 'Nâng cấp',
          'All_Applications': 'Tất cả đơn ứng tuyển',
          'Dark': 'Tối',
          'Light': 'Sáng',
          'Detail': 'Chi tiết',
          'Interview_Time': 'Thời gian phỏng vấn',
          'See_more': 'Xem thêm',
          'Collapse': 'Thu nhỏ',
          'Gender': 'Giới tính',
          'Male': 'Nam',
          'Female': 'Nữ',
          'Other': 'Khác',
          'Place_Job': 'Nơi muốn tìm việc ',
          'Less_Than': 'Ít hơn',
          'Year': 'Năm',
          'Introduction': 'Giới thiệu',
          'News_Recruitment': 'Tin ứng tuyển',
          'Company_Follow': 'Theo dõi',
          'Following': 'Đang theo dõi',
          'Content_Dialog_Unfollow':
              'Nếu bạn bỏ theo dõi, bạn sẽ không còn nhận tin công việc mới của công ty này. Bạn có muốn tiếp tục?',
          'Unfollow': 'Bỏ theo dõi',
          'Send_OTP': 'Gửi mã OTP',
          'Account_Authentication': 'Xác thực tài khoản',
          'Enter_the_verification_code_sent_to_your_email':
              'Nhập mã OTP đã gửi đến mail của bạn',
          'Get_OTP': 'Lấy mã OTP',
          'OTP_fail': 'OTP fail',
          'Something_Wrong': 'Có gì đó sai ở đây',
          'Resend_OTP': 'Gửi lại mã OTP',
          'Email_is_not_exist': 'Email không tồn tại',
          'Change_Password': 'Đổi mật khẩu',
          'New_Password': 'Mật khẩu mới',
          'Confirm_Password': 'Xác nhận lại mật khẩu',
          'I_agree_to_change_my_password.': 'Tôi đồng ý thay đổi mật khẩu.',
          'Password_changed_successfully!': 'Thay đổi mật khẩu thành công!',
          'Payment': 'Thanh toán',
          'month': 'Tháng',
          'year': 'Năm',
          'Only': 'Chỉ',
          'Day': 'Ngày',
          'Update_account_line1': 'Nâng cấp tài khoản của bạn',
          'Update_account_line2': 'Chọn gói của bạn',
          'Oder': 'Oder',
          'Payment_done': 'Thanh toán thành công',
          'You_will':
              'Hệ thống sẽ tự động chuyển hướng về màn hình chính sau một lúc \n hoặc ấn vào màn hình để trở lại',
          'Continue': 'Tiếp tục',
          'Pls_Email_And_Check': 'Vui lòng nhập email và đồng ý với Điều khoản',
          'Email_Exist':
              'Email này đã tồi tại trong JobsHunt. Bạn có muốn đăng nhập?  ',
          'Sign_Up_Failed': 'Đăng ký thất bại',
          'Yes': 'Có',
          'No': 'Không',
          'Headquarter': 'Trụ sở',
          'Check': 'Xem',
          'Thousands': 'Nghìn',
          'Millions': 'Triệu',
          'Billions': 'Tỷ',
          'No_Experience_Required': 'Không yêu cầu kinh nghiệm',
          'Delete': 'Xóa',
          'Pls_Enter_Password': 'Vui lòng nhập mật khẩu',
          'Need_6p_Char': 'Cân hơn 6 ký tự',
          'No_Space': 'Không được dùng cách',
          'And': 'Và',
          'Phone_Less_11': 'SĐT không được hơn 11 chữ số',
          'Phone_More_9': 'SĐT phải hơn 9 chữ số',
          'Chat': 'Nhắn tin',
          'Available_Job': 'Công việc hiện có',
          'Tax_Code': 'Mã số thuế',
          'Tax_Code_Must_10': 'Mã số thuế phải có 10 chữ số',
          'Message': 'Tin nhắn',
          'Edit': 'Chỉnh sửa',
          'Set_Time': 'Đặt giờ',
          'Set_Date': 'Đặt ngày',
          'Premium': 'Cao cấp',
          'Basic': 'Thông thường',
          'Number_Available_Jobs': 'Số công việc hiện có',
          'Reset': 'Đặt lại',
          'All_Companies': 'Tất cả công ty',
          'Premium_Expiry_Date': 'Ngày hết hạn của gói cao cấp',
          'Payment_History': 'Lịch sử thanh toán',
          'Type_bank': 'Loại thanh toán',
          'Price': 'Giá',
          'Date_Created': 'Ngày tạo',
          'STT': 'STT',
          'Term':
              '\t\t\tBằng cách truy cập hoặc sử dụng phần mềm FPL Work, các dịch vụ, hoặc bất kỳ ứng dụng nào do FPL Work (jobshunt.ino) cung cấp (gọi chung là "Dịch vụ"), dù truy cập bằng cách nào, bạn đồng ý chịu sự ràng buộc của Điều Khoản Sử Dụng với Người dùng này ("Điều Khoản Sử Dụng"). Dịch vụ do FPL Work sở hữu hoặc kiểm soát. Các Điều Khoản Sử Dụng này ảnh hưởng đến quyền và nghĩa vụ pháp lý của bạn. Nếu bạn không đồng ý chịu sự ràng buộc của tất cả các Điều Khoản Sử Dụng này, bạn không truy cập hay sử dụng Dịch vụ. Nếu Bạn có bất kỳ câu hỏi nào liên quan đến Điều Khoản này, vui lòng liên hệ chúng tôi.\n\t\t\tChúng tôi có thể cập nhật Điều Khoản Sử Dụng này theo thời gian vì các lý do pháp lý hoặc theo quy định hoặc để cho phép hoạt động thích hợp của phần mềm FPL Work. Mọi thay đổi sẽ được thông báo tới bạn bằng một thông báo phù hợp trên trang web của chúng tôi. Những thay đổi này sẽ áp dụng cho việc sử dụng trang web FPL Work. Sau khi chúng tôi đã thông báo đến bạn, Nếu bạn không muốn chấp nhận Điều Khoản Sử Dụng sau khi được cập nhật, bạn không nên tiếp tục sử dụng phần mềm FPL Work. Nếu bạn tiếp tục sử dụng phần mềm FPL Work kể từ ngày Điều Khoản Sử Dụng được cập nhật, bạn phải chấp thuận Điều Khoản Sử Dụng của FPL Work bằng cách lựa chọn đồng ý thông qua thông báo được hiển thị trên trang web của chúng tôi khi áp dụng các thay đổi.',
          'Reporting_Reason': 'Lý do báo cáo',
          'Other_Reasons': 'Lý do khác',
          'One_Reason': 'Bài đăng có dấu hiệu lừa đảo',
          'Two_Reason': 'Thông tin không chính xác',
          'Three_Reason': 'Điền lý do của bạn vào đây',
          'Report': 'Báo cáo',
          'Report_Company_Reminder':
              'Hãy tìm hiểu kỹ về công ty tuyển dụng và công việc bạn muốn ứng tuyển. Bạn nên cẩn trọng với những vấn đề như yêu cầu nộp phí, hoặc những hợp động mập mờ, không rõ ràng. Nếu bạn thấy rằng tin tuyển dụng của công ty này có sai phạm, hãy phán ánh với chúng tôi.',
          'Want_Exit': 'Bạn có muốn thoát?',
          'View_Profile': 'Xem Hồ Sơ',
          'Has': 'Có',
          'Warning':
              'Bạn đã đạt đến giới hạn của chức năng này. Vui lòng nâng cấp CAO CẤP nếu bạn muốn tiếp tục.',
          'CV_Full':
              'Bạn đã đạt đến giới hạn của Quản lý CV (Tối đa 3 CV/tài khoản). Vui lòng nâng cấp CAO CẤP nếu bạn muốn lưu trữ thêm.',
          'Report_User_Reminder':
              'Hãy tìm hiểu kỹ về ứng viên bạn muốn ứng tuyển. Bạn nên cẩn trọng với những vấn đề như spam, những hành động quấy rối, lạm dụng. Nếu bạn thấy rằng ứng viên này có sai phạm, hãy phán ánh với chúng tôi.',
          'Two_Reason_2': 'Hành động quấy rối, lạm dụng',
          'Splash_Title': 'Tìm công việc ước mơ',
          'Splash_Tile':
              'Tìm công việc mơ ước thật dễ dàng và nhanh chóng với FPLWork',
          'Get_Started': 'Bắt đầu nào',
          'Hold_Delete': 'Giữ CV mà bạn muốn xóa',
          'No_Available': 'Công việc này hiện không còn hoạt động.',
          'Require': 'Yêu cầu',
          'Thank You': 'Cảm Ơn',
          'This_Acc_Banned': 'Tài khoản này đã bị cấm bởi Quản Trị Viên.',
        },
      };
}
