import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Hello': 'Hello',
          'App_Name': 'JobsHunt',
          'Email': 'Email',
          'Password': 'Password',
          'Login': 'Login',
          'Search': 'Search',
          'Recommend_Job': 'Recommend Job',
          'Best_Job': 'Best Job',
          'Verified_Companies': 'Verified Companies',
          'No_Data': 'No Data',
          'Your_Profile': 'Your Profile',
          'Your_Inbox': 'Your Inbox',
          'Your_Job_Status': 'Your Job Status',
          'Your_Job_Saved': 'Your Job Saved',
          'Your_Following_Company': 'Your Following Company',
          'Job_Recommend_Setting': 'Job Recommend Setting',
          'Notification': 'Notification',
          'Setting': 'Setting',
          'About': 'About',
          'Exit': 'Exit',
          'Fullname': 'Fullname',
          'Display_Name': 'Display Name',
          'Phone': 'Phone',
          'Address': 'Address',
          'Province': 'Province',
          'District': 'District',
          'Ward': 'Ward',
          'Road_Street': 'Road/Street',
          'Birthday': 'Date of Birth',
          'Education': 'Education',
          'Want_Job': 'Want To Find Job',
          'Account_Level': 'Your Account Level',
          'Role': 'Role',
          'Salary': 'Salary',
          'Min_Salary': 'Min Salary',
          'Max_Salary': 'Max Salary',
          'Currency': 'Currency',
          'Done': 'Done',
          'Update': 'Update',
          'Select': 'Select',
          'Guest': 'Guest',
          'Successful': 'Successful',
          'Unsuccessful': 'Unsuccessful',
          'Not_Full_Data': 'Please add full data',
          'Sign_In_With': 'Sign in with',
          'Dont_Have_Acc': 'Don\'t have an account?',
          'Sign_Up_Now': 'Sign Up Now',
          'Or': 'Or',
          'Using_App_Without': 'Using app without an account',
          'Register': 'Register',
          'Have_Acc': 'You have an account?',
          'Sign_In_Now': 'Sign In Now',
          'Password_Again': 'Password Again',
          'Read_Accepted': 'I have read and accepted to the',
          'Terms_Conditions': 'Terms and Conditions',
          'Candidate': 'Candidate',
          'Recuiter': 'Recuiter',
          'Remember': 'Remember',
          'Forget_Pass': 'Forget Password',
          'Need_Same_Pass': 'Two Passwords must be same',
          'Email_Validation': 'Please enter a valid email address.',
          'You_Are': 'You are',
          'Welcome_to': 'Welcome to',
          'Please_Set_Role': 'Please set your role to continue.',
          'Cancel': 'Cancel',
          'ThatsRight': 'That\'s right',
          'Website': 'Website',
          'Description': 'Description',
          'OK': 'OK',
          'CV_Today': 'Signed CV Today',
          'Posted_Jobs': 'Your Posted Jobs',
        },
        'vi_VN': {
          'Hello': 'Xin Chào',
          'App_Name': 'JobsHunt',
          'Email': 'Email',
          'Password': 'Mật khẩu',
          'Login': 'Đăng nhập',
          'Search': 'Tìm Kiếm',
          'Recommend_Job': 'Công Việc Gợi Ý',
          'Best_Job': 'Công Việc Tốt Nhất',
          'Verified_Companies': 'Công Ty Được Xác Thực',
          'No_Data': 'Không Có Dữ Liệu',
          'Your_Profile': 'Hồ Sơ Của Bạn',
          'Your_Inbox': 'Hòm Thư Của Bạn',
          'Your_Job_Status': 'Tình Trạng Công Việc',
          'Your_Job_Saved': 'Công Việc Đã Lưu',
          'Your_Following_Company': 'Công Ty Đang Theo Dõi',
          'Job_Recommend_Setting': 'Cài Đặt Công Việc Gợi Ý',
          'Notification': 'Thông Báo',
          'Setting': 'Cài Đặt',
          'About': 'Giới Thiệu',
          'Exit': 'Thoát',
        },
      };
}
